# start: docker compose -f ./unifi-compose.yml up -d
# stop:  docker compose -f ./unifi-compose.yml down

version: "3"
services:
  unifi:
    image: jacobalberty/unifi:latest
    restart: unless-stopped
    ports:
      - "8080:8080"
      - "8443:8443"
      - "3478:3478/udp"
    environment:
      - TZ=Europe/Warsaw
    volumes:
      # adjust the path here
      - /home/chopeen/unifi:/unifi
    user: unifi
    init: true
  watchtower:
    image: containrrr/watchtower
    restart: unless-stopped
    # check every 12h
    command: --interval 43200
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      # uncomment if the Docker config exists, e.g. it may store credetials for private registries
      # example: https://containrrr.dev/watchtower/usage-overview/
      # - /root/.docker/config.json:/config.json
